dataloader:
  _target_: lib.dataset.XHumans_scan.XHumansDataModule
  dataset_path: /path/to/XHumans/dataset/person_ID
  use_pca: false
  num_pca_comps: 0
  flat_hand_mean: false
  num_workers: 4
  batch_size: 4

processor:
  _target_: lib.dataset.XHumans_scan.XHumansDataProcessor
  points_per_frame: 6000
  representation: occ
  category_sample: true
  sampler:
    _target_: lib.model.sample.PointInSpace
    global_sigma: 1.8
    local_sigma: 0.01
